# Generated by Django 5.2.6 on 2025-09-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Remove the problematic dependency to 0001_initial
        # Keep this empty since we're starting fresh
    ]

    operations = [
        # These operations are likely empty since the models were moved to other apps
        # If there are any operations here, they should be cleanup operations
        # that don't depend on the deleted 0001_initial migration
    ]